// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PQJ_p_P9kjpErlxx1aDbys75iLB8o7o',
    appId: '1:754041145265:web:aae2929c51382fa416df90',
    messagingSenderId: '754041145265',
    projectId: 'kino-rant',
    authDomain: 'kino-rant.firebaseapp.com',
    storageBucket: 'kino-rant.firebasestorage.app',
    measurementId: 'G-ER8W16P75Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJA2xDQWg6rk0FuMvWhc1zUIxO_G5_nGg',
    appId: '1:754041145265:android:0bcfefef6d59c24616df90',
    messagingSenderId: '754041145265',
    projectId: 'kino-rant',
    storageBucket: 'kino-rant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdaGzreqcTXu0SRCuWaDGuQTgfAqnNhhI',
    appId: '1:754041145265:ios:d9f2ccccaf25cb1216df90',
    messagingSenderId: '754041145265',
    projectId: 'kino-rant',
    storageBucket: 'kino-rant.firebasestorage.app',
    iosBundleId: 'com.example.kinoRant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdaGzreqcTXu0SRCuWaDGuQTgfAqnNhhI',
    appId: '1:754041145265:ios:d9f2ccccaf25cb1216df90',
    messagingSenderId: '754041145265',
    projectId: 'kino-rant',
    storageBucket: 'kino-rant.firebasestorage.app',
    iosBundleId: 'com.example.kinoRant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0PQJ_p_P9kjpErlxx1aDbys75iLB8o7o',
    appId: '1:754041145265:web:d6b10c8d9398f5b716df90',
    messagingSenderId: '754041145265',
    projectId: 'kino-rant',
    authDomain: 'kino-rant.firebaseapp.com',
    storageBucket: 'kino-rant.firebasestorage.app',
    measurementId: 'G-03PCR2GZXS',
  );
}
